modified on real time

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -39,7 +39,7 @@ jobs:
             echo "::error ::GitHub token is missing or not passed properly!"
             exit 1
           else
-            echo "✅ GitHub token is set. Length: ${#TF_VAR_github_token}"
+            echo "GitHub token is set. Length: ${#TF_VAR_github_token}"
           fi
         env:
           TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
@@ -49,7 +49,9 @@ jobs:
         env:
           TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
         run: |
-          terraform destroy -target=module.amplify_app -auto-approve || echo "Nothing to destroy"
+          terraform destroy -target=module.amplify_app.aws_amplify_domain_association.domain -auto-approve || echo "Domain not found or already deleted"
+          terraform destroy -target=module.amplify_app.aws_amplify_branch.main_branch -auto-approve || echo "Branch not found or already deleted"
+          terraform destroy -target=module.amplify_app.aws_amplify_app.this -auto-approve || echo "App not found or already deleted"
 
       - name: Terraform Apply
         working-directory: ./envs/dev
