Updated the key from oauth for git access

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -32,17 +32,17 @@ jobs:
             -backend-config="bucket=eastghats-ccp-terraform-state-dev" \
             -backend-config="key=dev/terraform.tfstate" \
             -backend-config="region=eu-west-2"
-      
-            - name: 🔍 Debug GitHub token length
-            run: |
-              if [ -z "$TF_VAR_github_token" ]; then
-                echo "::error ::GitHub token is missing or not passed properly!"
-                exit 1
-              else
-                echo "✅ GitHub token is set. Length: ${#TF_VAR_github_token}"
-              fi
-            env:
-              TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
+
+      - name: 🔍 Debug GitHub token length
+        run: |
+          if [ -z "$TF_VAR_github_token" ]; then
+            echo "::error ::GitHub token is missing or not passed properly!"
+            exit 1
+          else
+            echo "✅ GitHub token is set. Length: ${#TF_VAR_github_token}"
+          fi
+        env:
+          TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
 
       - name: Terraform Apply
         working-directory: ./envs/dev
